name: Comment when opened
on:
  issues:
    types: [opened, reopened]
jobs:
  verify-issue:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: View context attributes
        id: check
        uses: actions/github-script@v6
        with:
          # Add labels to an issue
          # https://docs.github.com/en/rest/issues/labels#add-labels-to-an-issue
          script: |
            console.log(context)
            const body = context.payload.issue.body
            if (body && body.toLowerCase().includes("body")) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting!'
              })
              return 'help wanted'
            }
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, new contributor!

                Please make sure you're read our [README](README.md) and we look forward to reviewing your Pull request shortly ✨`
            })
            return 'invalid'
          result-encoding: string
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.check.outputs.result }}
  close-issue:
    runs-on: ubuntu-latest
    needs: verify-issue
    if: ${{ success() && needs.verify-issue.outputs.result == 'invalid' }}
    steps:
      - name: close issue
        # Using GitHub CLI in workflows
        # https://docs.github.com/cn/actions/using-workflows/using-github-cli-in-workflows
        run: gh issue close $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

