name: Comment when opened
on:
  issues:
    types:
      - opened
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step1.outputs.body }}
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
          
