name: Comment when opened
on:
  issues:
    types:
      - opened
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step1.outputs.body }}
    steps:
      - id: step1
        run: echo "::set-output name=body::${{ github.event.issue.body }}"
      - run: echo "issue title ${{ github.event.issue.title }}"
      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
  verify-body:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      # if: ${{ contains(needs.job1.outputs.output, "body" ) }}
      - run: echo "${{ needs.job1.outputs.output }}"
          
